name: Generate HKET Feed

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate_feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have dependencies

      - name: Run script to generate feed
        run: python hknet.py 

      - name: Upload feed to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: hket_feed.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
